<div style="text-align:center; margin-top:20px">
    <p>
        <b> Error Handling Operators - catchError():</b>
       
        RxJS also provides a few operators to handle the error thrown by the source observable. The error handling
        operators are catchError(), retry() and retryWhen(). We will focus here only on catchError() operator.

        catchError() :-
        catchError() operator will help in catching the errors from the source observable by returning a new observable
        or throwing an error.
    </p>
</div>

<div style="text-align:center; margin-top:20px">
    <p>
        <b>retry():-</b>
    </p>
</div>
